apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: x509-certificate-exporter
    app.kubernetes.io/part-of: victoria-metrics-operator
    app.kubernetes.io/version: 3.13.0
  name: x509-certificate-exporter
  namespace: monitoring-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: x509-certificate-exporter
      app.kubernetes.io/part-of: victoria-metrics-operator
  template:
    metadata:
      annotations:
        prometheus.io/port: "9793"
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/component: exporter
        app.kubernetes.io/name: x509-certificate-exporter
        app.kubernetes.io/part-of: victoria-metrics-operator
        app.kubernetes.io/version: 3.13.0
    spec:
      containers:
        - args:
            - --listen-address=:9793
            - --trim-path-components=3
            - --watch-file=/mnt/watch/control-plane-certs//etc/kubernetes/pki/apiserver.crt
            - --watch-file=/mnt/watch/control-plane-certs//etc/kubernetes/pki/apiserver-etcd-client.crt
            - --watch-file=/mnt/watch/control-plane-certs//etc/kubernetes/pki/apiserver-kubelet-client.crt
            - --watch-file=/mnt/watch/control-plane-certs//etc/kubernetes/pki/ca.crt
            - --watch-file=/mnt/watch/control-plane-certs//etc/kubernetes/pki/front-proxy-ca.crt
            - --watch-file=/mnt/watch/control-plane-certs//etc/kubernetes/pki/front-proxy-client.crt
            - --watch-file=/mnt/watch/control-plane-certs//etc/kubernetes/pki/etcd/ca.crt
            - --watch-file=/mnt/watch/control-plane-certs//etc/kubernetes/pki/etcd/healthcheck-client.crt
            - --watch-file=/mnt/watch/control-plane-certs//etc/kubernetes/pki/etcd/peer.crt
            - --watch-file=/mnt/watch/control-plane-certs//etc/kubernetes/pki/etcd/server.crt
            - --watch-kubeconf=/mnt/watch/control-plane-certs//etc/kubernetes/admin.conf
            - --watch-kubeconf=/mnt/watch/control-plane-certs//etc/kubernetes/controller-manager.conf
            - --watch-kubeconf=/mnt/watch/control-plane-certs//etc/kubernetes/scheduler.conf
            - --watch-kubeconf=/mnt/watch/control-plane-certs//etc/kubernetes/kubelet.conf
            - --max-cache-duration=300s
          image: enix/x509-certificate-exporter:3.13.0
          imagePullPolicy: IfNotPresent
          name: x509-certificate-exporter
          ports:
            - containerPort: 9793
              name: metrics
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 40Mi
            requests:
              cpu: 10m
              memory: 20Mi
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsGroup: 0
            runAsUser: 0
          volumeMounts:
            - mountPath: /mnt/watch/control-plane-certs//etc/kubernetes
              name: control-plane-certs
              readOnly: true
      dnsConfig:
        options:
          - name: ndots
            value: "0"
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      serviceAccount: x509-certificate-exporter
      tolerations:
        - operator: Exists
      volumes:
        - hostPath:
            path: /etc/kubernetes/
            type: Directory
          name: control-plane-certs
