apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: x509-certificate-exporter
    app.kubernetes.io/part-of: victoria-metrics-operator
    app.kubernetes.io/version: 3.13.0
  name: x509-certificate-exporter
  namespace: monitoring-system
spec:
  clusterIP: None
  ports:
    - name: metrics
      port: 9793
      targetPort: metrics
  selector:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: x509-certificate-exporter
    app.kubernetes.io/part-of: victoria-metrics-operator
