apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: x509-certificate-exporter
    app.kubernetes.io/part-of: victoria-metrics-operator
    app.kubernetes.io/version: 3.13.0
  name: x509-certificate-exporter
  namespace: monitoring-system
