apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: kube-summary-exporter
    app.kubernetes.io/part-of: victoria-metrics-operator
  name: kube-summary-exporter
rules:
  - apiGroups: [""]
    resources: ["nodes/proxy"]
    verbs: ["get"]
