apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: kube-summary-exporter
    app.kubernetes.io/part-of: victoria-metrics-operator
    app.kubernetes.io/version: 0.4.3
  name: kube-summary-exporter
  namespace: monitoring-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: kube-summary-exporter
      app.kubernetes.io/part-of: victoria-metrics-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/component: exporter
        app.kubernetes.io/name: kube-summary-exporter
        app.kubernetes.io/part-of: victoria-metrics-operator
        app.kubernetes.io/version: 0.4.3
    spec:
      containers:
      - image: quay.io/utilitywarehouse/kube-summary-exporter:v0.4.3
        name: kube-summary-exporter
        ports:
        - containerPort: 9779
          name: metrics
        resources:
          limits:
            cpu: 250m
            memory: 250Mi
          requests:
            cpu: 100m
            memory: 150Mi
      dnsConfig:
        options:
        - name: ndots
          value: "0"
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: kube-summary-exporter
      tolerations:
      - operator: Exists
