apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: kube-summary-exporter
    app.kubernetes.io/part-of: victoria-metrics-operator
  name: kube-summary-exporter
  namespace: monitoring-system
spec:
  clusterIP: None
  ports:
  - name: metrics
    port: 9779
    targetPort: metrics
  selector:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: kube-summary-exporter
    app.kubernetes.io/part-of: victoria-metrics-operator
