apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/name: vmagent
    app.kubernetes.io/part-of: victoria-metrics-operator
  name: vmagent
  namespace: monitoring-system
