apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlert
metadata:
  labels:
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/name: vmalert
    app.kubernetes.io/part-of: victoria-metrics-operator
    app.kubernetes.io/version: 1.100.0
  name: rule
  namespace: monitoring-system
spec:
  datasource:
    url: "http://vmsingle-tsdb.monitoring-system.svc.cluster.local:8429"
  dnsConfig:
    options:
      - name: ndots
        value: "0"
  evaluationInterval: "30s"
  extraArgs:
    loggerLevel: INFO
  image:
    repository: victoriametrics/vmalert
    tag: v1.100.0
    pullPolicy: IfNotPresent
  nodeSelector:
    node-role.kubernetes.io/monitoring: ""
  notifier:
    url: "blackhole"
  podMetadata:
    labels:
      app.kubernetes.io/component: monitoring
      app.kubernetes.io/name: vmalert
      app.kubernetes.io/part-of: victoria-metrics-operator
      app.kubernetes.io/version: 1.100.0
  selectAllByDefault: true
  remoteWrite:
    url: "http://vmsingle-tsdb.monitoring-system.svc.cluster.local:8429"
    concurrency: 100
    flushInterval: 5s
    maxBatchSize: 100000
    maxQueueSize: 10000000
  replicaCount: 1
  resources:
    requests:
      cpu: "250m"
      memory: "100Mi"
    limits:
      cpu: "500m"
      memory: "500Mi"
  tolerations:
    - operator: Exists
