apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/name: monitoring-system
    app.kubernetes.io/part-of: victoria-metrics-operator
  name: monitoring-system
