apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: ping-exporter
    app.kubernetes.io/part-of: victoria-metrics-operator
    app.kubernetes.io/version: 1.1.3
  name: ping-exporter
  namespace: monitoring-system
spec:
  clusterIP: None
  ports:
    - name: http
      port: 9427
      targetPort: http
  selector:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: ping-exporter
    app.kubernetes.io/part-of: victoria-metrics-operator
