apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/name: vmsingle-node-access
    app.kubernetes.io/part-of: victoria-metrics-operator
  name: vmsingle-node-access
  namespace: monitoring-system
spec:
  ports:
  - name: http
    nodePort: 31429
    port: 8429
    targetPort: 8429
  selector:
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/name: vmsingle
    app.kubernetes.io/part-of: victoria-metrics-operator
  type: NodePort
