apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/name: victoria-metrics-operator
    app.kubernetes.io/part-of: victoria-metrics-operator
    app.kubernetes.io/version: 0.42.4
  name: victoria-metrics-operator
  namespace: monitoring-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: monitoring
      app.kubernetes.io/name: victoria-metrics-operator
      app.kubernetes.io/part-of: victoria-metrics-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/component: monitoring
        app.kubernetes.io/name: victoria-metrics-operator
        app.kubernetes.io/part-of: victoria-metrics-operator
        app.kubernetes.io/version: 0.42.4
    spec:
      containers:
        - args:
            - --enable-leader-election
          command:
            - manager
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: VM_USECUSTOMCONFIGRELOADER
              value: "true"
            - name: OPERATOR_NAME
              value: victoria-metrics-operator
          image: victoriametrics/operator:v0.42.4
          name: manager
          resources:
            requests:
              cpu: 250m
              memory: 250Mi
            limits:
              cpu: 500m
              memory: 1000Mi
      dnsConfig:
        options:
          - name: ndots
            value: "0"
      nodeSelector:
        node-role.kubernetes.io/monitoring: ""
      serviceAccountName: victoria-metrics-operator
      terminationGracePeriodSeconds: 10
      tolerations:
        - operator: Exists
