apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/name: victoria-metrics-operator
    app.kubernetes.io/part-of: victoria-metrics-operator
  name: victoria-metrics-operator
  namespace: monitoring-system
